[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ciberedev.py"
authors = [{name = "cibere", email = "cibere@cibere.cibere"}]
dynamic = ["version", "description"]
